import Head from 'next/head'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Pharos Claim </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Pharos.jpg" />
      </Head>

      <main className=' flex flex-col justify-items-stretch'>
        <div className=' flex flex-row items-center justify-between shadow-lg mb-9'>
          <div className=' m-2'>
            <img src='Pharos.jpg' className=' h-28 w-28 m-7'></img>
          </div>
          <div>
            <p className=' m-2 mr-16 via-blue-600 font-bold text-xl text-green-900 lg:text-5xl '> منصة جامعة فاروس القانونيه</p>
          </div>
        </div>
        
        <div className=' self-center mt-7 '>
          <p className=' font-semibold font-serif text-lg align-middle'>يسعدنا استقبال الشكاوي من حضراتكم علي هذه المنصة </p>
        </div>
        <form className=' flex flex-col m-4'  >


          <div className=' flex  bg-slate-300 rounded-md flex-col lg:flex-row '>

            <div className=' bg-slate-300 p-4 w-1/2 rounded-md'>
               <label for="fname" >First name:</label>
               <input type='text' id='fName' name='fName' 
                className=' rounded-full m-4 h-10 w-fit text-center text-slate-700 '
          
               >

              </input>

            </div>
            <div className=' bg-slate-300 p-4 w-1/2' >
               <label for="lname">Last name:</label>
               <input type='text' id='lName' name='lName' 
                  className=' rounded-full m-4 h-10 w-fit text-slate-700 text-center'
          
               >

              </input>

            </div>

            <div className=' bg-slate-300 p-4 w-1/2 rounded-md'>
               <label for="mNumber">Mobile Number:</label>
               <input type='text' id='mNumber' name='mNumber' 
                  className=' rounded-full m-4 h-10 w-fit text-slate-700 text-center'
          
               >

              </input>

            </div>

          </div>
          <div className=' flex bg-slate-300 mt-5 p-7 rounded-md'>
            <label for='claim'>Your Calim:</label>
            <input type='text' name='claim' id='claim' className=' w-full rounded-xl p-2 text-center border-none m-4 h-16 text-slate-700 ' ></input>
          </div>
          <div className='self-center mt-12 bg-black text-yellow-200 rounded-md '>
            <button className='p-5 rounded-xl text-center font-extrabold' >Apply</button>
          </div>
         
        </form>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}
