import Head from 'next/head'


import {React , useRef} from 'react'

import { db } from '../firebase'

import {doc , setDoc , addDoc , getFirestore, collection , }from 'firebase/firestore'


export default function Home() {

  
  const fName = useRef(null)
  const lName = useRef(null)
  const mNumber = useRef(null)
  const claim = useRef(null)

  function subForm (e) {
      e.preventDefault()
     let firstName = fName.current.value
     let lastname = lName.current.value
     let phonenum = mNumber.current.value
     let claimU = claim.current.value

     console.log(firstName.length);
     let data={}
     if(firstName.length != "" & lastname.length != "" & phonenum != '' & claimU != '' ){
      let data = {
          ffname : firstName ,
          llname : lastname ,
          ppnumber : phonenum ,
          claimUm : claimU,

      }
      //********************************************************************************************************* */
      // adding document to firebase 
      const dataRef = collection (db , "patient")
      addDoc(dataRef , {

          ffname : firstName ,
          llname : lastname ,
          ppnumber : phonenum ,
          claimUm : claimU,


      })
         
     //******************************************************************************************* */
      console.log(data);
      fName.current.value = ''
      lName.current.value = ''
      mNumber.current.value = ''
      claim.current.value =''
     }else {
         alert('يجب ملئ جميع البيانات ')
     }

    }
  return (
    <div >
      <Head>
        <title>Pharos Claim </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Pharos.jpg" />
      </Head>
 
      <main className=' flex flex-col justify-items-stretch'>
        <div className=' flex flex-row items-center justify-between shadow-lg mb-9'>
          <div className=' m-2'>
            <img src='Pharos.jpg' className=' h-28 w-28 m-7'></img>
          </div>
          <div>
            <p className=' m-2  via-blue-600 font-bold text-xl text-green-900 lg:text-5xl '> منصة جامعة فاروس القانونيه</p>
          </div>
        </div>
        
        <div className=' self-end mt-7 p-3 '>
          <p className=' font-semibold font-serif text-xs lg:text-lg '>يسعدنا استقبال الشكاوي من حضراتكم علي هذه المنصة </p>
        </div>
        <form className=' flex flex-col m-4'  >


          <div className=' flex  bg-slate-300 rounded-md flex-col lg:flex-row '>

            <div className=' bg-slate-300 p-4 w-1/2 rounded-md'>
               <label for="fName" >First name:</label>
               <input ref={fName} type='text' id='fName' name='fName' 
                className=' rounded-full m-4 h-10 w-fit text-center text-slate-700 '
          
               >

              </input>

            </div>
            <div className=' bg-slate-300 p-4 w-1/2' >
               <label for="lname">Last name:</label>
               <input ref={lName} type='text' id='lName' name='lName' 
                  className=' rounded-full m-4 h-10 w-fit text-slate-700 text-center'
          
               >

              </input>

            </div>

            <div className=' bg-slate-300 p-4 w-1/2 rounded-md'>
               <label for="mNumber">Mobile Number:</label>
               <input  ref={mNumber} type='text' id='mNumber' name='mNumber' 
                  className=' rounded-full m-4 h-10 w-fit text-slate-700 text-center'
          
               >

              </input>

            </div>

          </div>
          <div className=' flex bg-slate-300 mt-5 p-7 rounded-md flex-col'>
            <label for='claim'>Your Calim:</label>
            <input ref={claim} type='text' name='claim' id='claim' className=' rounded-xl p-2 text-center border-none m-4 h-16 text-slate-700 w-full ' ></input>
          </div>
          <div className='self-center mt-12 bg-black text-yellow-200 rounded-md '>
            <button onClick={subForm} className='p-5 rounded-xl text-center font-extrabold' >Apply</button>
          </div>
         
        </form>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}
